// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avlbgesqjzhbcojukrnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2bGJnZXNxanpoYmNvanVrcm5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MDE2NDQsImV4cCI6MjA2MTQ3NzY0NH0.--asrHh88xns9NsE02qRBPV8FKCzJUF9TnzJlJnYDoo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);